service: api-statistics-service
frameworkVersion: '>=1.44.0'

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or falls back to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  projectName: P300

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-1
  environment:
    tableName: ${file(../api-infrastructure/serverless.yml):custom.generalTableName}
  apiGateway:
    restApiId:
      'Fn::ImportValue': ${self:custom.stage}-P300-ApiGatewayRestApiId
    restApiRootResourceId:
      'Fn::ImportValue': ${self:custom.stage}-P300-ApiGatewayRestApiRootResourceId
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - '*'

plugins:
  - serverless-offline
  - serverless-webpack

functions:
  createStatisticsDayForEachUni:
    handler: src/handler.createStatisticsDayForEachUni
    events:
      - schedule: rate(15 minutes)
  getStatisticsDayById:
    handler: src/handler.getStatisticsDayById
    events:
      - http:
          path: /statistics/{statisticsId}
          method: get
          cors: true
          authorizer: aws_iam
  getAllTotalStatsForOneUni:
    handler: src/handler.getAllTotalStatsForOneUni
    events:
      - http:
          path: /statistics/university/total/{universityId}
          method: get
          cors: true
          authroizer: aws_iam
  getForDateRangeOneUni:
    handler: src/handler.getForDateRangeOneUni
    events:
      - http:
          path: /statistics/university/{universityId}
          method: get
          cors: true
          authorizer: aws_iam
  getAllTotalForDateRangeAllUni:
    handler: src/handler.getAllTotalForDateRangeAllUni
    events:
      - http:
          path: /statistics/all
          method: get
          cors: true
          authorizer: aws_iam
  getTotalsForEachMonthOneUni:
    handler: src/handler.getTotalsForEachMonthOneUni
    events:
      - http:
          path: /statistics/university/months/{universityId}
          method: post
          cors: true
          authorizer: aws_iam
    

resources:
  - ${file(../resources/cognito-policy.yml)}
