service: api-infrastructure
frameworkVersion: ">=1.60.0"

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1
  stage: dev
  tags:
    project: project300
    
custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or falls back to what we have set in the provider section.
  stage: ${opt.stage, self:provider.stage}
  generalTableName: P300-GENERAL
  projectName: P300

plugins:
  - serverless-offline
  - serverless-webpack

functions:
  preSignUp:
    handler: src/handler.preSignUp
    events:
      - cognitoUserPool:
          pool: ${self:custom.stage}-${self:custom.projectName}Pool
          trigger: PreSignUp
          existing: true
  postConfirmation:
    handler: src/handler.postConfirmation
    events:
      - cognitoUserPool:
          pool: ${self:custom.stage}-${self:custom.projectName}Pool
          trigger: PostConfirmation
          existing: true

resources:
  - ${file(resources/dynamodb-tables.yml)}
  - ${file(resources/cognito.yml)}
  - ${file(resources/api-gateway.yml)}