service:
  name: Project-300

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1
  stage: dev
  tags:
    project: project300

  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:Scan"
      Resource: "*"
    - Effect: Allow
      Action:
        - "execute-api:ManageConnections"
      Resource:
        - "arn:aws:execute-api:*:*:**/@connections/*"

functions:
  connectHandler:
    handler: src/$connect/connect.connectHandler
    events:
      - websocket:
          route: $connect
  disconnectHandler:
    handler: src/$disconnect/disconnect.disconnectHandler
    events:
      - websocket:
          route: $disconnect
  defaultHandler:
    handler: src/$default/default.defaultHandler
    events:
      - websocket:
          route: $default
  sendMessageHandler:
    handler: src/functions/messages/message.sendMessageHandler
    events:
      - websocket:
          route: sendMessage
  signupHandler:
    handler: src/functions/signup/signup.signupHandler
    events:
      - websocket:
          route: signup
  confirmationHandler:
    handler: src/functions/confirmation/confirmation.confirmationHandler
    events:
      - websocket:
          route: confirmAccount
  loginHandler:
    handler: src/functions/login/login.loginHandler
    events:
      - websocket:
          route: login

resources:
  Resources:
    ConnectionTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: "connectionId"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "connectionId"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST
        TableName: ConnectionIds
    CognitoTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: "cognitoId"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "cognitoId"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST
        TableName: CognitoData
    UserTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: "UserId"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "UserId"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST
        TableName: P300_USERS
