service:
  name: Project-300

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1
  stage: dev
  tags:
    project: project300

  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:Scan"
      Resource:
        - Fn::GetAtt: [ConnectionTable, Arn]
    - Effect: Allow
      Action:
        - "execute-api:ManageConnections"
      Resource:
        - "arn:aws:execute-api:*:*:**/@connections/*"

functions:
  connectHandler:
    handler: src/$connect/connect.connectHandler
    events:
      - websocket:
          route: $connect
  disconnectHandler:
    handler: src/$disconnect/disconnect.disconnectHandler
    events:
      - websocket:
          route: $disconnect
  defaultHandler:
    handler: src/$default/default.defaultHandler
    events:
      - websocket:
          route: $default
  sendMessageHandler:
    handler: src/functions/messages/message.sendMessageHandler
    events:
      - websocket:
          route: sendMessage

resources:
  Resources:
    ConnectionTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: "connectionId"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "connectionId"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST
        TableName: ConnectionIds
