Resources:
  ConnectionTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: 'connectionId'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'connectionId'
          KeyType: 'HASH'
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.stage}-P300-ConnectionIds
  CognitoTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: 'cognitoId'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'cognitoId'
          KeyType: 'HASH'
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.stage}-CognitoData
  SubscriptionTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: 'subscriptionName'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'subscriptionName'
          KeyType: 'HASH'
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.stage}-P300-SUBSCRIPTIONS
  GeneralTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: 'pk'
          AttributeType: 'S'
        - AttributeName: 'sk'
          AttributeType: 'S'
        - AttributeName: 'entity'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'pk'
          KeyType: 'HASH'
        - AttributeName: 'sk'
          KeyType: 'RANGE'
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.stage}-${self:custom.generalTableName}
      GlobalSecondaryIndexes:
        - IndexName: entity-sk-index
          KeySchema:
            - AttributeName: entity
              KeyType: HASH
            - AttributeName: sk
              KeyType: RANGE
          Projection:
            ProjectionType: "ALL"


Outputs:
  ConnectionTable:
    Value:
      Ref: ConnectionTable
    Export:
      Name: ${self:custom.stage}-ConnectionTable
  CognitoTable:
    Value:
      Ref: CognitoTable
    Export:
      Name: ${self:custom.stage}-CognitoTable
  SubscriptionTable:
    Value:
      Ref: SubscriptionTable
    Export:
      Name: ${self:custom.stage}-SubscriptionTable
  GeneralTable:
    Value:
      Ref: GeneralTable
    Export:
      Name: ${self:custom.stage}-${self:custom.generalTableName}
  
