service: api-university-service
frameworkVersion: ">=1.44.0"

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or falls back to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  projectName: P300

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-1
  environment:
    tableName: ${file(../api-infrastructure/serverless.yml):custom.generalTableName}
  apiGateway:
    restApiId:
      'Fn::ImportValue': ${self:custom.stage}-P300-ApiGatewayRestApiId
    restApiRootResourceId:
      'Fn::ImportValue': ${self:custom.stage}-P300-ApiGatewayRestApiRootResourceId
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - '*'

plugins:
  - serverless-offline
  - serverless-webpack

functions:
  getAllUniversities:
    handler: src/handler.getAllUniversities
    events:
      - http:
          path: /universities
          method: get
          cors: true
          authorizer: aws_iam
  getUniversityById:
    handler: src/handler.getUniversityById
    events:
      - http:
          path: /universities/{universityId}/{universityName}
          method: get
          cors: true
          authorizer: aws_iam
  getAllUniversityDomains:
    handler: src/handler.getAllUniversityDomains
    events:
      - http:
          path: /universities/domains
          method: get
          cors: true
          authorizer: aws_iam
  createUniversity:
    handler: src/handler.createUniversity
    events:
      - http:
          path: /universities
          method: post
          cors: true
          authorizer: aws_iam
  updateUniversity:
    handler: src/handler.updateUniversity
    events:
      - http:
          path: /universities
          method: put
          cors: true
          authorizer: aws_iam
  deleteUniversity:
    handler: src/handler.deleteUniversity
    events:
      - http:
          path: /universities/{universityId}/{universityName}
          method: delete
          cors: true
          authorizer: aws_iam

resources:
    - ${file(../resources/cognito-policy.yml)}

