service: api-driver-application-service
frameworkVersion: ">=1.44.0"

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or falls back to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-1
  environment:
    tableName: ${file(../api-infrastructure/serverless.yml):custom.generalTableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - '*'

plugins:
  - serverless-offline
  - serverless-webpack

functions:
  getAllNonConfirmedApplications:
    handler: src/handler.getAllNonConfirmedApplications
    events:
      - http:
          path: /driver-applications
          method: get
          cors: true
  getApplicationByUserId:
    handler: src/handler.getApplicationByUserId
    events:
      - http:
          path: /driver-applications/{userId}
          method: get
          cors: true
  applyForApplication:
    handler: src/handler.applyForApplication
    events:
      - http:
          path: /driver-applications/apply
          method: post
          cors: true
  checkIfUserHasApplied:
    handler: src/handler.checkIfUserHasApplied
    events:
      - http:
          path: /driver-applications/check/{userId}
          method: get
          cors: true
  createApplication:
    handler: src/handler.createApplication
    events:
      - http:
          path: /driver-applications
          method: post
          cors: true
  approveApplication:
    handler: src/handler.approveApplication
    events:
      - http:
          path: /driver-applications/approve
          method: patch
          cors: true
  deleteApplication:
    handler: src/handler.deleteApplication
    events:
      - http:
          path: /driver-applications/{userId}
          method: delete
          cors: true

