service: api-driver-application-service
frameworkVersion: ">=1.44.0"

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or falls back to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  projectName: P300

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-1
  apiGateway:
    restApiId:
      'Fn::ImportValue': ${self:custom.stage}-P300-ApiGatewayRestApiId
    restApiRootResourceId:
      'Fn::ImportValue': ${self:custom.stage}-P300-ApiGatewayRestApiRootResourceId
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - '*'

plugins:
  - serverless-offline
  - serverless-webpack

functions:
  #query string of approved true or false else it will get all
  getAllApplications:
    handler: src/handler.getAllApplications
    events:
      - http:
          path: /driver-applications
          method: get
          cors: true
          authorizer: aws_iam
  getApplicationByUserId:
    handler: src/handler.getApplicationByUserId
    events:
      - http:
          path: /driver-applications/{userId}
          method: get
          cors: true
          authorizer: aws_iam
  applyForApplication:
    handler: src/handler.applyForApplication
    events:
      - http:
          path: /driver-applications/apply
          method: post
          cors: true
          authorizer: aws_iam
  checkIfUserHasApplied:
    handler: src/handler.checkIfUserHasApplied
    events:
      - http:
          path: /driver-applications/check/{userId}
          method: get
          cors: true
          authorizer: aws_iam
  createApplication:
    handler: src/handler.createApplication
    events:
      - http:
          path: /driver-applications
          method: post
          cors: true
          authorizer: aws_iam
  approveApplication:
    handler: src/handler.approveApplication
    events:
      - http:
          path: /driver-applications/approve
          method: patch
          cors: true
          authorizer: aws_iam
  deleteApplication:
    handler: src/handler.deleteApplication
    events:
      - http:
          path: /driver-applications/{userId}
          method: delete
          cors: true
          authorizer: aws_iam

resources:
    - ${file(../resources/cognito-policy.yml)}

